### ISSUE TITLE
InputAdjustを使用すると判定とエフェクトにズレが生じる

### ISSUE THREAD

**Issue by AioiLight** [AioiLight/TJAPlayer3#198]
**Describe the bug**
#180 でマージされたコミット後、InputAdjustを使用すると判定と判定に対応したエフェクトにズレが生じるようになりました。

**To Reproduce**
1. Config から InputAdjustの値を変更 (e.g. 99 or -99)に変更する
(大きな値に変更している意味は、違いがはっきりと分かるためです。
2. 適当な曲をプレイする。
3. オートかどうかに関わらず、判定は良なのに可のエフェクトが出たり、不可なのに音符が飛んでいったりする。

**Expected behavior**
判定自体に問題が起こるわけではないようです。見た目だけの変化です。

**Screenshots**
![20181029184132](https://user-images.githubusercontent.com/13918537/47641800-5ada9d80-dbaa-11e8-8e83-46af959ec974.png)
![20181029184147](https://user-images.githubusercontent.com/13918537/47641821-64fc9c00-dbaa-11e8-8665-0f2d329e73db.png)

**Desktop (please complete the following information):**

- Ryzen 1700
- 16GB RAM
- GTX 1060 6GB
- Windows 10 (1803)

**Additional context**
スキンによる違いではありません。
エフェクト系に渡る判定が正常ではない???

**Comment by twopointzero** [comment]
I was able to reproduce the note sometimes not flying, using both:
* large negative input adjust (via ~100ms audio latency and -99ms input adjustment to account for it) and
* large positive input adjust (via that same ~100ms audio latency but with a specially-crafted offset file so that I could use +99ms input adjustment to account for "playing in the future")

(Negative offset seemed more sensitive to this than positive offset. Low refresh rate and VSyncWait=1 was also more sensitive to this than high refresh rate and/or VSyncWait=0.)

Interestingly, this issue is not present in PR #197, suggesting that the instinct I had to change where input adjustment was being handled was a good instinct. :) It also suggests that the really old input adjustment code never worked properly, as I didn't do more than bring it back online.

Please try to reproduce using the PR #197 branch. I suspect the problem will go away. If it persists, please let me know your monitor refresh rate, VSyncWait setting, monitor G-Sync or FreeSync, audio output type, audio output latency, etc.

**Comment by AioiLight** [comment]
I tried to reproduce the same problem using PR # 197, but the problem did not occur and the judgment and the effect were synchronized.
Pull requests will be approved at the time.

**Comment by twopointzero** [comment]
I'm glad to hear that the newer code is working well for you. It is certainly far simpler logically and (by acting just like the user striking the drum earlier or later while running with buffered input) should produce more consistent results all around.

**Comment by twopointzero** [comment]
@AioiLight We should be able to close this issue now.

**Comment by AioiLight** [comment]
InputAdjustは変更されたので、クローズ。
