### ISSUE TITLE
DoublePlay時の譜面パースの不具合

### ISSUE THREAD

**Issue by AioiLight** [AioiLight/TJAPlayer3#205]
多分 #189 のPR以降譜面パースに不具合(もしくは仕様)が発生している。

シングルプレイ時の譜面とダブルプレイ時の譜面が異なる(e.g. ハレ晴レユカイ、夏祭り)場合、譜面は1Pの共通譜面が流れた後、音源が再度再生され(#START nPの再生)、ダブルプレイ専用の譜面が流れる様になる。

このPRではダブルプレイ時のふうせん連打が正しく反映されない不具合を修正しているが、それについては問題ない( = 正しくパースされている)。

**Comment by AioiLight** [comment]
```
(前略)
#START
12121212,
#END

STYLE:Double(Couple)
#START P1
21212121,
#END
#START P2
11112222,
#END
```

といった書き方をすると再現可能。

**Comment by AioiLight** [comment]
COURSE:Oni
STYLE:Single
#START
～
#END

STYLE:Double
#START P1
21212121,
#END
#START P2
11112222,
#END

では、Single時の譜面が再生されない。
Double時は問題ない。

**Comment by twopointzero** [comment]
This seems to boil down to the suffix of "(Couple)"

I could easily update the regular expression to allow any text after "Single" or "Double", for example. How flexible would you like the code to be?

**Comment by AioiLight** [comment]
太鼓さん次郎のreadme.htmlでは
> STYLE
>     「Single」「Double」「Couple」もしくは1～2の数字を入力。
> 
>     Singleは一人プレイ、DoubleとCoupleは二人プレイの譜面であることを示します。DoubleとCoupleの違いはありません。 
> 
>     Double（Couple）のあとに#START P1、#START P2を入れることで1P側と2P側で違う譜面を入力することができます。 譜面選択の際に1Pと2Pで違うコースを選択した場合、二人プレイ用の譜面が存在していても一人プレイ用の譜面が流れます。 

と書かれています。

singleでもSingleでも、DoubleでもDOUBLEでも正常にパースされます。
```
STYLE:Double // hogehoge
```
のように、コメントがあってもパースされます。

**Comment by twopointzero** [comment]
Thanks for the details. I'm working on it now.

**Comment by twopointzero** [comment]
I was able to address the primary issue quite easily today, though there were some complications adding test automation (due mostly to our still being on .net 3.5.)

A secondary issue remains outstanding. I'll need some more time to come up with the best solution for it as it will greatly complicate this parsing code. Eventually, we should migrate to a properly-constructed parser but now is not quite the right time. In the meantime, I am trying to account for certain types of poorly-formed files that do occur in the wild from time to time. Specifically: files with STYLE:Double music sheets for P1 and P2 but which do not use STYLE:Single properly for their single player music sheet. I'll keep working on a way to do this without overly convoluting the code or becoming too tempted to user a parser generator. :)

**Comment by twopointzero** [comment]
Good progress on nearly rewriting the code, though still based on the concept removing STYLE sections and music sheets which are not needed, rather than splitting and extracting.
* It no longer leaves the player without any music sheet. It'll at least try to choose the most appropriate one.
* It will no longer leave more than one music sheet in place. No more charts repeating after the BGM finishes.
* It is now even more flexible than was requested. It makes sense to make this code as flexible as it can possibly be while still parsing things safely. For example, it now accepts missing or extra whitespace in and around command delimeters. It now accepts trailing characters on many of the involved commands. It can now detect doubles play #START P1 and #START P2 commands that aren't even in a STYLE section, though it will prioritize ones that are in a STYLE section. It can fall back on a STYLE:Single sheet or even a sheet at the top level of the document if P1 needs a sheet but the STYLE:Double section only contains a #START P2 command. The list goes on and on. :)

I'm not quite ready to open a PR:
* I have an improvement I want to try to make regarding header values which appear between the STYLE command and the START which follows it.
* I also want to add some more tests (I have 18 test files which multiply out to 54 test cases (18 files * seqNo 0, 1, and 2,) and there are a few more I'd like to add before considering things done.)

But if in the meantime you are curious as to the general approach now being taken, here's the design outline I worked from, and which held its truth all the way through implementation:
1. Break the string up into top-level sections of the following types:
  a) STYLE Single
  b) STYLE Double/Couple
  c) STYLE unrecognized
  d) non-STYLE
2. Within the top-level sections, break each up into sub-sections of the following types:
  a) sheet START P1
  b) sheet START P2
  c) sheet START bare
  d) sheet START unrecognized
  e) non-sheet
3. For the current seqNo, rank the found sheets using a per-seqNo set of rankings for each relevant section/subsection combination.
4. Determine the best-ranked sheet
5. Remove sheets other than the best-ranked
6. Remove supported top-level STYLE-type sections which no longer contain a sheet
7. Reassemble the string

I'll try to wrap this work up a bit later this week and open a PR, likely by Friday in Japan.
